version: "2"
services:
  moneway:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/nknab/Moneway
    container_name: moneway
    ports:
      - 8000:8000
    links:
      - transaction:transaction
      - balance:balance
    depends_on:
      - transaction
      - balance
  balance:
    build:
      context: .
      dockerfile: api/services/balance/Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/nknab/Moneway
    container_name: balance
    ports:
      - 8082:8082
  transaction:
    build:
      context: .
      dockerfile: api/services/transaction/Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/nknab/Moneway
    container_name: transaction
    ports:
      - 8081:8081
    depends_on:
      - balance
