version: "2"
services:
  balance:
    build:
      context: .
      dockerfile: balance/Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/nknab/Moneway
    container_name: balance
    ports:
      - 8800:8082
  transactions:
    build:
      context: .
      dockerfile: transactions/Dockerfile
    restart: always
    volumes:
      - .:/go/src/github.com/nknab/Moneway
    container_name: transactions
    ports:
      - 8801:8081
  etcd:
    image: "quay.io/coreos/etcd:v3.1.7"
    restart: always
    ports:
      - "23791:2379"
      - "23801:2380"
    environment:
      ETCD_NAME: infra
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd:2380"
      ETCD_INITIAL_CLUSTER: infra=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: secrettoken
      ETCD_LISTEN_CLIENT_URLS: "http://etcd:2379,http://localhost:2379"
      ETCD_LISTEN_PEER_URLS: "http://etcd:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
