// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/nknab/MonewayV1.0/transactions/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	TransctEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.TransactionsService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{TransctEndpoint: MakeTransctEndpoint(s)}
	for _, m := range mdw["Transct"] {
		eps.TransctEndpoint = m(eps.TransctEndpoint)
	}
	return eps
}
