// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/nknab/MonewayV1.0/balance/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetBalanceEndpoint    endpoint.Endpoint
	UpdateBalanceEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.BalanceService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GetBalanceEndpoint:    MakeGetBalanceEndpoint(s),
		UpdateBalanceEndpoint: MakeUpdateBalanceEndpoint(s),
	}
	for _, m := range mdw["GetBalance"] {
		eps.GetBalanceEndpoint = m(eps.GetBalanceEndpoint)
	}
	for _, m := range mdw["UpdateBalance"] {
		eps.UpdateBalanceEndpoint = m(eps.UpdateBalanceEndpoint)
	}
	return eps
}
