#/*
# * File: config.toml
# * Project: Moneway Go Developper Intern Challenge
# * File Created: Friday, 15th March 2019 7:49:00 PM
# * Author: nknab
# * Email: kojo.anyinam-boateng@outlook.com
# * Version: 1.1
# * Brief:
# * -----
# * Last Modified: Friday, 15th March 2019 7:49:02 PM
# * Modified By: nknab
# * -----
# * Copyright ©2019 nknab
# */
#docker.for.mac.

[database]
server = "localhost"
port = "3306"
database = "moneway"
user = "root"
password = ""


[ports]
    [ports.main]
    port = "8000"

    [ports.transaction]
    port = "8081"

    [ports.balance]
    port = "8082"