/*
 * File: config.toml
 * Project: Moneway Go Developper Intern Challenge
 * File Created: Friday, 15th March 2019 7:49:00 PM
 * Author: nknab
 * Email: kojo.anyinam-boateng@outlook.com
 * Version: 1.1
 * Brief: 
 * -----
 * Last Modified: Friday, 15th March 2019 7:49:02 PM
 * Modified By: nknab
 * -----
 * Copyright ©2019 nknab
 */

[database]
server = "docker.for.mac.localhost"
port = "3306"
database = "moneway"
user = "root"
password = ""