# /*
#  * File: config.toml
#  * Project: Moneway Intern Assesment
#  * File Created: Monday, 11th March 2019 7:05:40 AM
#  * Author: nknab
#  * Email: kojo.anyinam-boateng@outlook.com
#  * Version: 1.0
#  * Brief: 
#  * -----
#  * Last Modified: Monday, 11th March 2019 9:24:50 AM
#  * Modified By: nknab
#  * -----
#  * Copyright ©2019 nknab
#  */

# filename: config.toml
[database]
server = "127.0.0.1"
port = "3306"
database = "moneway"
user = "root"
password = ""