// Code generated by protoc-gen-go. DO NOT EDIT.
// source: balance.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBalanceRequest struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{0}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

type GetBalanceReply struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceReply) Reset()         { *m = GetBalanceReply{} }
func (m *GetBalanceReply) String() string { return proto.CompactTextString(m) }
func (*GetBalanceReply) ProtoMessage()    {}
func (*GetBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{1}
}

func (m *GetBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceReply.Unmarshal(m, b)
}
func (m *GetBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceReply.Marshal(b, m, deterministic)
}
func (m *GetBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceReply.Merge(m, src)
}
func (m *GetBalanceReply) XXX_Size() int {
	return xxx_messageInfo_GetBalanceReply.Size(m)
}
func (m *GetBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceReply proto.InternalMessageInfo

func (m *GetBalanceReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type UpdateBalanceRequest struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalanceRequest) Reset()         { *m = UpdateBalanceRequest{} }
func (m *UpdateBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceRequest) ProtoMessage()    {}
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{2}
}

func (m *UpdateBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceRequest.Unmarshal(m, b)
}
func (m *UpdateBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceRequest.Merge(m, src)
}
func (m *UpdateBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceRequest.Size(m)
}
func (m *UpdateBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceRequest proto.InternalMessageInfo

func (m *UpdateBalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *UpdateBalanceRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type UpdateBalanceReply struct {
	Success              string   `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalanceReply) Reset()         { *m = UpdateBalanceReply{} }
func (m *UpdateBalanceReply) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceReply) ProtoMessage()    {}
func (*UpdateBalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee25a00b628521b1, []int{3}
}

func (m *UpdateBalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceReply.Unmarshal(m, b)
}
func (m *UpdateBalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceReply.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceReply.Merge(m, src)
}
func (m *UpdateBalanceReply) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceReply.Size(m)
}
func (m *UpdateBalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceReply proto.InternalMessageInfo

func (m *UpdateBalanceReply) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBalanceRequest)(nil), "pb.GetBalanceRequest")
	proto.RegisterType((*GetBalanceReply)(nil), "pb.GetBalanceReply")
	proto.RegisterType((*UpdateBalanceRequest)(nil), "pb.UpdateBalanceRequest")
	proto.RegisterType((*UpdateBalanceReply)(nil), "pb.UpdateBalanceReply")
}

func init() { proto.RegisterFile("balance.proto", fileDescriptor_ee25a00b628521b1) }

var fileDescriptor_ee25a00b628521b1 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0xcc, 0x49,
	0xcc, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe4,
	0x12, 0x74, 0x4f, 0x2d, 0x71, 0x82, 0x88, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9,
	0x70, 0x71, 0x26, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x78, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x21, 0x04, 0x94, 0x34, 0xb9, 0xf8, 0x91, 0xb5, 0x14, 0xe4, 0x54, 0x0a, 0x89, 0x71,
	0xb1, 0x25, 0xe6, 0x82, 0xa4, 0xa1, 0xaa, 0xa1, 0x3c, 0x25, 0x1f, 0x2e, 0x91, 0xd0, 0x82, 0x94,
	0xc4, 0x92, 0x54, 0x52, 0x2c, 0x40, 0x32, 0x8d, 0x09, 0xc5, 0x34, 0x3d, 0x2e, 0x21, 0x34, 0xd3,
	0x40, 0x76, 0x4b, 0x70, 0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x43, 0x4d, 0x82, 0x71,
	0x8d, 0xda, 0x18, 0xb9, 0xd8, 0xa1, 0x4a, 0x85, 0x2c, 0xb8, 0xb8, 0x10, 0x8e, 0x16, 0x12, 0xd5,
	0x2b, 0x48, 0xd2, 0xc3, 0xf0, 0xb7, 0x94, 0x30, 0xba, 0x30, 0xc8, 0x7c, 0x47, 0x2e, 0x5e, 0x14,
	0x5b, 0x85, 0x24, 0x40, 0xaa, 0xb0, 0x79, 0x4b, 0x4a, 0x0c, 0x8b, 0x4c, 0x41, 0x4e, 0x65, 0x12,
	0x1b, 0x38, 0xbc, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0x2d, 0x36, 0x0e, 0x80, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceClient interface {
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceReply, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceReply, error)
}

type balanceClient struct {
	cc *grpc.ClientConn
}

func NewBalanceClient(cc *grpc.ClientConn) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceReply, error) {
	out := new(GetBalanceReply)
	err := c.cc.Invoke(ctx, "/pb.Balance/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceReply, error) {
	out := new(UpdateBalanceReply)
	err := c.cc.Invoke(ctx, "/pb.Balance/UpdateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServer is the server API for Balance service.
type BalanceServer interface {
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceReply, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceReply, error)
}

func RegisterBalanceServer(s *grpc.Server, srv BalanceServer) {
	s.RegisterService(&_Balance_serviceDesc, srv)
}

func _Balance_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Balance/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Balance/UpdateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Balance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Balance_GetBalance_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _Balance_UpdateBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balance.proto",
}
